global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: ctoa-mobile-console
    metrics_path: /metrics
    static_configs:
      - targets: ["ctoa:8787"]

  - job_name: prometheus
    static_configs:
      - targets: ["ctoa-prometheus:9090"]