-- ctoa_helper_profile_persistence.lua [CTOA OTClient Native]
-- Passive profile persistence policy. This module never loads, saves, or migrates profile files.

local ProfilePersistence = rawget(_G, "CTOA_HELPER_PROFILE_PERSISTENCE") or {}

local PROFILE_CANDIDATES = {
    "/ctoa_user_ek_profile.lua",
    "user_dir/ctoa_otclient/ctoa_ek_profile.lua",
    "ctoa_otclient/ctoa_ek_profile.lua",
    "/ctoa_ek_profile.lua",
}

local UI_PREFS_CANDIDATES = {
    "/ctoa_user_ui_prefs.lua",
    "user_dir/ctoa_otclient/ctoa_ui_prefs.lua",
    "ctoa_otclient/ctoa_ui_prefs.lua",
    "/ctoa_ui_prefs.lua",
}

local SAVE_DEFAULTS = {
    profile = {
        file_name = "ctoa_ek_profile.lua",
        work_dir_suffix = "ctoa_user_ek_profile.lua",
        root_key = "profile",
        header = "-- ctoa_ek_profile.lua\n" ..
            "-- Generated by ctoa_native_helper.lua live profile builder.\n" ..
            "-- Edit by the helper UI, not by hand.\n\n",
        dirty_status = "Autosave: pending",
        clean_status = "Autosave: saved",
        dirty_reason_prefix = "Profile changed: ",
        save_failed_status = "Profile save failed",
        saved_status = "Profile saved",
        autosave_delay_ms = 450,
    },
    ui_prefs = {
        file_name = "ctoa_ui_prefs.lua",
        work_dir_suffix = "ctoa_user_ui_prefs.lua",
        root_key = "ui_prefs",
        header = "-- ctoa_ui_prefs.lua\n" ..
            "-- Generated by ctoa_native_helper.lua live UI prefs builder.\n" ..
            "-- Edit by the helper UI, not by hand.\n\n",
        dirty_status = "Autosave: pending",
        clean_status = "Autosave: saved",
        save_failed_status = "UI prefs save failed",
        saved_status = "UI prefs saved",
        autosave_delay_ms = 450,
    },
}

local FALLBACK_PROFILE_EXPORT_SECTIONS = {
    healing = {
        "spell_enabled",
        "potion_enabled",
        "spell_threshold",
        "potion_threshold",
        "threshold_jitter_percent",
        "spell",
        "critical_spell",
        "spell_rotation",
        "potion_name",
        "potion_mode",
        "potion_hotkey",
        "potion_actionbar_slot",
        "mana_potion_enabled",
        "mana_potion_threshold",
        "mana_potion_name",
        "mana_potion_hotkey",
        "mana_potion_actionbar_slot",
        "mana_potion_cooldown_ms",
        "cooldown_ms",
    },
    heal_friend = {
        "enabled",
        "observe_party",
        "sio_spell",
        "hp_threshold",
        "cooldown_ms",
        "action_lock_ms",
        "friend_whitelist",
        "friend_target_id",
        "priority",
        "require_whitelist",
        "pz_safe",
        "runtime_enabled",
        "friend_scan_range",
        "sample_interval_ms",
        "last_sample_ms",
        "last_status",
        "observed_count",
        "lowest_friend_hp",
        "last_cast_ms",
    },
    conditions = {
        "enabled",
        "observe_states",
        "mana_shield",
        "paralyze",
        "poison",
        "burn",
        "electric",
        "bleeding",
        "runtime_enabled",
        "sample_interval_ms",
        "api_probe_enabled",
        "api_probe_status",
        "api_probe_count",
        "last_sample_ms",
        "last_status",
    },
    equipment = {
        "enabled",
        "observe_slots",
        "ring_swap",
        "amulet_swap",
        "family_enabled",
        "weapon_set",
        "pvp_gear_lock",
        "hp_threshold",
        "sample_interval_ms",
        "api_probe_enabled",
        "api_probe_status",
        "api_probe_count",
        "runtime_enabled",
        "last_sample_ms",
        "last_status",
    },
    scripting = {
        "enabled",
        "policy_mode",
        "allow_user_snippets",
        "allow_runtime_eval",
        "command_model",
        "audit_log",
        "sandbox_required",
        "max_snippet_chars",
        "runtime_enabled",
        "last_status",
    },
    tools = {
        "auto_attack",
        "chase",
        "auto_follow",
        "pause_in_pz",
        "hold_target",
        "require_reachable_target",
        "attack_range",
        "target_timeout_ms",
        "unreachable_timeout_ms",
        "retarget_delay_ms",
        "log_retarget_ms",
        "block_log_ms",
        "probe_log_ms",
        "clear_target_in_pz",
        "block_npc_icons",
        "block_friendly_summons",
        "friendly_summon_name_fragments",
        "ignored_names",
        "prefer_low_hp",
        "priority_names",
        "auto_haste",
        "haste_spell",
        "haste_interval_ms",
        "api_probe_enabled",
        "magic_api_probe_enabled",
        "spell_rotation",
        "magic_priority",
        "rotation_preset",
        "rotation_interval_ms",
        "rotation_scan_range",
        "recovery_action_gap_ms",
        "rotation_spells",
        "auto_exeta",
        "exeta_interval_ms",
        "exeta_min_visible",
        "exeta_spells",
        "auto_stance",
        "offensive_buff_spell",
        "defensive_buff_spell",
        "offensive_max_monsters",
        "defensive_min_monsters",
        "stance_cooldown_ms",
        "last_stance_ms",
        "active_stance",
        "rune_enabled",
        "rune_name",
        "rune_hotkey",
        "rune_actionbar_slot",
        "rune_min_visible",
        "rune_cooldown_ms",
        "rune_pvp_safe",
        "rune_requires_target",
        "timer_enabled",
        "timer_interval_ms",
        "timer_message",
        "last_timer_ms",
        "auto_open_corpses",
        "auto_loot_containers",
        "loot_range",
        "loot_capacity_threshold",
        "loot_max_items_per_scan",
        "cavebot_api_probe_enabled",
        "cavebot_enabled",
        "cavebot_movement_enabled",
        "cavebot_step_delay_ms",
        "cavebot_reach_distance",
        "cavebot_retry_limit",
        "cavebot_waypoints",
        "feature_flags",
        "diagnostics_export_limit",
        "diagnostics_sample_interval_ms",
    },
}

local function copyList(values)
    local result = {}
    for index, value in ipairs(values or {}) do
        result[index] = value
    end
    return result
end

local function copyTable(value)
    if type(value) ~= "table" then
        return value
    end
    local result = {}
    for key, item in pairs(value) do
        result[key] = copyTable(item)
    end
    return result
end

local function saveDefaults(kind)
    return copyTable(SAVE_DEFAULTS[tostring(kind or "")] or {})
end

local function exportSection(config, sectionName, fields)
    local section = type(config) == "table" and config[sectionName] or nil
    local result = {}
    if type(section) ~= "table" then
        return result
    end
    for _, field in ipairs(fields or {}) do
        result[field] = section[field]
    end
    return result
end

local function profileExportDescriptors()
    local schema = rawget(_G, "CTOA_HELPER_PROFILE_SCHEMA")
    if type(schema) == "table" and type(schema.profileExportDescriptors) == "function" then
        local ok, descriptors = pcall(schema.profileExportDescriptors)
        if ok and type(descriptors) == "table" and #descriptors > 0 then
            return copyTable(descriptors)
        end
    end
    local descriptors = {}
    local order = {"healing", "heal_friend", "conditions", "equipment", "scripting", "tools"}
    for index, sectionName in ipairs(order) do
        descriptors[index] = {
            id = sectionName,
            source = sectionName,
            output = sectionName,
            fields = copyList(FALLBACK_PROFILE_EXPORT_SECTIONS[sectionName] or {}),
            generated = true,
        }
    end
    return descriptors
end

function ProfilePersistence.profileExportDescriptors()
    return profileExportDescriptors()
end

function ProfilePersistence.profilePersistenceValue(functionName, fallback, ...)
    local callback = rawget(ProfilePersistence, tostring(functionName or ""))
    if type(callback) == "function" and
        callback ~= ProfilePersistence.profilePersistenceValue and
        callback ~= ProfilePersistence.profilePersistenceTable then
        local ok, value = pcall(callback, ...)
        if ok and value ~= nil then
            return value
        end
    end
    return fallback
end

function ProfilePersistence.profilePersistenceTable(functionName, fallback, ...)
    local value = ProfilePersistence.profilePersistenceValue(functionName, fallback, ...)
    if type(value) == "table" then
        return value
    end
    return type(fallback) == "table" and fallback or {}
end

function ProfilePersistence.profileCandidates()
    return copyList(PROFILE_CANDIDATES)
end

function ProfilePersistence.uiPrefsCandidates()
    return copyList(UI_PREFS_CANDIDATES)
end

function ProfilePersistence.saveDefaults(kind)
    return saveDefaults(kind)
end

local function mutableFileName(kind, path)
    local defaults = saveDefaults(kind)
    local file = string.match(tostring(path or ""), "([^/\\]+)$") or tostring(defaults.file_name or "")
    if kind == "ui_prefs" then return "ctoa_user_ui_prefs.lua" end
    if string.sub(file, 1, 10) == "ctoa_user_" then return file end
    local vocation = string.match(file, "ctoa_([a-z][a-z])_profile%.lua$")
    if vocation then
        local prefix = string.gsub(file, "ctoa_" .. vocation .. "_profile%.lua$", "")
        return "ctoa_user_" .. prefix .. vocation .. "_profile.lua"
    end
    return "ctoa_user_ek_profile.lua"
end

function ProfilePersistence.resolveSavePath(kind, explicitPath, workDir)
    local defaults = saveDefaults(kind)
    local explicit = tostring(explicitPath or "")
    local work = tostring(workDir or "")
    if work ~= "" and string.sub(work, -1) ~= "/" and string.sub(work, -1) ~= "\\" then
        work = work .. "/"
    end
    if explicit ~= "" then
        if work ~= "" and not string.match(explicit, "^[A-Za-z]:[/\\]") then
            return work .. mutableFileName(kind, explicit)
        end
        return explicit
    end
    if work ~= "" and type(defaults.work_dir_suffix) == "string" then
        return work .. defaults.work_dir_suffix
    end
    return tostring(defaults.file_name or "")
end

function ProfilePersistence.fallbackSavePath(kind, attemptedPath)
    local defaults = saveDefaults(kind)
    local fallback = tostring(defaults.file_name or "")
    if tostring(attemptedPath or "") ~= fallback then
        return fallback
    end
    return ""
end

function ProfilePersistence.saveText(kind, serialized)
    local defaults = saveDefaults(kind)
    return tostring(defaults.header or "") .. "return " .. tostring(serialized or "nil") .. "\n"
end

function ProfilePersistence.loadSuccessText(kind, pathOrName)
    if kind == "ui_prefs" then
        return "UI prefs loaded: " .. tostring(pathOrName or "")
    end
    return "Profile loaded: " .. tostring(pathOrName or "")
end

function ProfilePersistence.loadFailureText(kind, path, err)
    if kind == "ui_prefs" then
        return "UI prefs load failed: " .. tostring(path or "") .. " " .. tostring(err or "")
    end
    return "Profile load failed: " .. tostring(path or "") .. " " .. tostring(err or "")
end

local function booleanPref(value)
    return value == true or value == "true" or value == 1
end

local function nonEmptyText(value)
    if type(value) == "string" and value ~= "" then
        return value
    end
    return nil
end

function ProfilePersistence.uiPrefsPlan(prefs, config, helpers)
    local data = type(prefs) == "table" and prefs or {}
    local cfg = type(config) == "table" and config or {}
    local helperApi = type(helpers) == "table" and helpers or {}
    local plan = {
        config_updates = {},
        hud_updates = {},
        helper_updates = {},
    }
    local hotkey = nonEmptyText(data.hotkey)
    if hotkey and type(helperApi.normalize_hotkey) == "function" then
        hotkey = helperApi.normalize_hotkey(hotkey)
    end
    if hotkey and hotkey ~= "" then
        plan.config_updates.hotkey = hotkey
    end
    if data.auto_hide_ms ~= nil then
        plan.config_updates.auto_hide_ms = tonumber(data.auto_hide_ms) or cfg.auto_hide_ms
    end
    if data.window_x ~= nil then
        plan.config_updates.window_x = tonumber(data.window_x) or cfg.window_x
    end
    if data.window_y ~= nil then
        plan.config_updates.window_y = tonumber(data.window_y) or cfg.window_y
    end
    if type(data.hud) == "table" then
        local hud = type(cfg.hud) == "table" and cfg.hud or {}
        if data.hud.enabled ~= nil then
            plan.hud_updates.enabled = booleanPref(data.hud.enabled)
        end
        if data.hud.x ~= nil then
            plan.hud_updates.x = tonumber(data.hud.x) or hud.x
        end
        if data.hud.y ~= nil then
            plan.hud_updates.y = tonumber(data.hud.y) or hud.y
        end
    end
    local theme = nonEmptyText(data.theme_preset)
    if theme then
        plan.config_updates.theme_preset = theme
    end
    if data.compact_mode ~= nil then
        plan.config_updates.compact_mode = booleanPref(data.compact_mode)
    end
    for _, key in ipairs({"active_tab", "smoke_tab", "smoke_subtab"}) do
        local value = nonEmptyText(data[key])
        if value then
            plan.helper_updates[key] = value
        end
    end
    return plan
end

function ProfilePersistence.dirtyState(kind, reason)
    local defaults = saveDefaults(kind)
    local state = {
        dirty_status = tostring(defaults.dirty_status or "Autosave: pending"),
        delay_ms = tonumber(defaults.autosave_delay_ms) or 450,
        log_text = "",
    }
    if reason and tostring(reason) ~= "" and type(defaults.dirty_reason_prefix) == "string" then
        state.log_text = defaults.dirty_reason_prefix .. tostring(reason)
    end
    return state
end

function ProfilePersistence.exportProfile(config, profileName)
    local cfg = type(config) == "table" and config or {}
    local tools = type(cfg.tools) == "table" and cfg.tools or {}
    local profile = {
        schema_version = cfg.schema_version or "ctoa-helper-profile-v1",
        vocation = cfg.vocation,
        name = profileName or "Built-in EK",
        enabled = cfg.enabled,
        safe_boot_runtime_disabled = cfg.safe_boot_runtime_disabled,
        tick_ms = cfg.tick_ms,
        modules = copyTable(cfg.modules or {}),
    }
    for _, descriptor in ipairs(profileExportDescriptors()) do
        if descriptor.generated == true then
            profile[descriptor.output] = exportSection(cfg, descriptor.source, descriptor.fields)
        end
    end
    profile.tools.magic_priority = tools.magic_priority or "rotation"
    profile.tools.rotation_preset = tools.rotation_preset or "smart"
    return profile
end

function ProfilePersistence.exportUiPrefs(config, helper)
    local cfg = type(config) == "table" and config or {}
    local ctx = type(helper) == "table" and helper or {}
    local hud = type(cfg.hud) == "table" and cfg.hud or {}
    return {
        hotkey = cfg.hotkey,
        auto_hide_ms = cfg.auto_hide_ms,
        theme_preset = cfg.theme_preset or "classic",
        compact_mode = cfg.compact_mode and true or false,
        window_x = cfg.window_x or 520,
        window_y = cfg.window_y or 34,
        active_tab = ctx.active_tab or "overview",
        hud = {
            enabled = hud.enabled or false,
            x = hud.x or 22,
            y = hud.y or 170,
        },
    }
end

function ProfilePersistence.contract()
    return {
        module = "ctoa_helper_profile_persistence",
        mode = "passive",
        owns_load_candidates = true,
        owns_save_path_policy = true,
        owns_save_headers = true,
        owns_autosave_metadata = true,
        owns_load_status_text = true,
        owns_ui_prefs_plan = true,
        owns_fallback_save_path = true,
        owns_export_profile = true,
        owns_profile_export_descriptors = true,
        owns_export_ui_prefs = true,
        owns_persistence_value_bridge = true,
        owns_persistence_table_bridge = true,
        runtime_actions = false,
        loads_files = false,
        saves_files = false,
        migrates_files = false,
        writes_profile = false,
        touches_otclient_globals = false,
        preserves_key_order = true,
        requires_profile_schema = true,
        requires_profile_audit = true,
        requires_safe_boot_defaults = true,
    }
end

_G.CTOA_HELPER_PROFILE_PERSISTENCE = ProfilePersistence

return ProfilePersistence
